### ISSUE TITLE
can you include the config files for git?

### ISSUE THREAD

**Issue by jmjava** [joshlong/bootiful-microservices#4]

**Comment by magaton** [comment]
+1 Eureka service cannot start 
2016-02-03 18:29:01.443 ERROR 21552 --- [kaServer.main()] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://localhost:8761/eureka/apps/
Can't contact any eureka nodes - possibly a security group issue?

com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to localhost:8761 timed out

I guess it requires some config, which is not found locally.

**Comment by marcingrzejszczak** [comment]
The configuration files are here - https://github.com/joshlong/bootiful-microservices-config
